In [ ]:
# 1. 신생아 이름 데이터를 이용하여 다음과 같은 분석을 진행하시오.
# -유명인, 성서에 등장하는 이름 등 외부 이름을 이용하여 이름 유행을 분석
# -각 연도별 가장 인기 있는 이름을 분석
# -다음 이름의 연도별 순위 조사(john, sophia, michael, daniel, carter)
# -각 연도별, 성별 상위 50% 이름을 구성하는 알파벳 문자 중, 자음과 모음의 비율 분석
# -가장 긴 이름과 가장 짧은 이름을 출력

In [7]:
import pandas as pd
import numpy as np

pieces=[]
for year in range(1880,2011):
    # 모든 연도 data 출력
    path='names/names/yob%d.txt' % year
    df=pd.read_csv(path, names=['name','sex','births'])
    # year column 추가
    df['year']=year
    # 빈 list에 모든 data 추가
    pieces.append(df)
#모든 df 병합
names=pd.concat(pieces,ignore_index=True)

In [34]:
#-유명인, 성서에 등장하는 이름 등 외부 이름을 이용하여 이름 유행을 분석
names

              name sex  births  year      prop
0             Mary   F    7065  1880  0.035064
1             Anna   F    2604  1880  0.012924
2             Emma   F    2003  1880  0.009941
3        Elizabeth   F    1939  1880  0.009623
4           Minnie   F    1746  1880  0.008666
...            ...  ..     ...   ...       ...
1690779    Zymaire   M       5  2010  0.000001
1690780     Zyonne   M       5  2010  0.000001
1690781  Zyquarius   M       5  2010  0.000001
1690782      Zyran   M       5  2010  0.000001
1690783      Zzyzx   M       5  2010  0.000001

[1690784 rows x 5 columns]

In [53]:
# -각 연도별 가장 인기 있는 이름을 분석
def get_pop(group):
    return group.sort_index(by='births',ascending=False)[:1000]

grouped=names.groupby(['year'])
pop_name=grouped.apply(get_pop)
pop_name.reset_index(inplace=True,drop=True)

pop_name.pivot_table(index='year',,values='name')

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  This is separate from the ipykernel package so we can avoid doing imports until

DataError: No numeric types to aggregate